apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  labels:
    app: kafka
spec:
  type: LoadBalancer
  ports:
    - port: 9092
      targetPort: tcp-kafka-int
      protocol: TCP
      name: kafka
  selector:
    app: kafka
  sessionAffinity: ClientIP
  externalTrafficPolicy: Local
