services:
  broker-1: &broker-base
    image: apache/kafka:3.9.1
    user: root
    ports:
      - "11092:9092"
    environment: &broker-env
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker-1:19093,2@broker-2:19093,3@broker-3:19093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:19093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:11092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LOG_DIRS: /opt/kafka/logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - kafka-1:/opt/kafka/logs
    healthcheck:
      test: /kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server kafka:9092 || exit 1
      interval: 5s
      timeout: 300s
      retries: 60

  broker-2:
    <<: *broker-base
    ports:
      - "11093:9092"
    environment:
      <<: *broker-env
      KAFKA_NODE_ID: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:11093
    volumes:
      - kafka-2:/opt/kafka/logs

  broker-3:
    <<: *broker-base
    ports:
      - "11094:9092"
    environment:
      <<: *broker-env
      KAFKA_NODE_ID: 3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:11094
    volumes:
      - kafka-3:/opt/kafka/logs

volumes:
  kafka-1:
  kafka-2:
  kafka-3:
